#ifndef _FSYSDEF_H_
#define _FSYSDEF_H_


#define BLOCK_SIZE 4096
#define DISK_CACHE_SIZE 32
#define DISK_CACHE_HASH_MULT 37
#define INODE_CACHE_SIZE 1024
#define INODE_CACHE_HASH_MULT 1117
#define OFT_HASH_SIZE 1024
#define OFT_HASH_MULT 1117
#define OFT_HASH_SIZE 100
#define OFT_HASH_MULT 113
#define MAX_FILE_NAME_LENGTH 20
#define MAX_PATH_LENGTH 200
#define INODE_BASE_SIZE 12

#define MAX_CONFIG_FILE_SIZE 512
#define DISK_CONFIG_FILE "diskconf.txt"

#define DISK_FILE "mydisk.img"
#define SUPERBLOCK_NO 0



#endif
